using System;
using System.Collections.Generic;
using UnityEngine;

namespace DeepEarth.Core
{
    public class LocalizationManager : MonoBehaviour
    {
        private static LocalizationManager _instance;
        public static LocalizationManager Instance
        {
            get
            {
                if (_instance == null)
                {
                    var go = new GameObject("LocalizationManager");
                    _instance = go.AddComponent<LocalizationManager>();
                    DontDestroyOnLoad(go);
                }
                return _instance;
            }
        }

        public string CurrentLanguageCode => SaveManager.CurrentData.Language;

        public event Action OnLanguageChanged;

        private readonly Dictionary<string, Dictionary<string, string>> _translations = new Dictionary<string, Dictionary<string, string>>();

        private void Awake()
        {
            if (_instance == null)
            {
                _instance = this;
                DontDestroyOnLoad(gameObject);
                InitializeTranslations();
            }
            else
            {
                Destroy(gameObject);
            }
        }

        private void InitializeTranslations()
        {
            // English translations
            var en = new Dictionary<string, string>
            {
                { "hud_hp", "HP: {0} / {1}" },
                { "hud_depth", "Depth: {0}m" },
                { "hud_bag", "Bag: {0} / {1}" },
                { "hud_iron", "Iron: {0}" },
                { "hud_silver", "Silver: {0}" },
                { "hud_gold", "Gold: {0}" },
                { "hud_diamond", "Diamond: {0}" },
                { "hud_inv_full", "Inventory Full!" },
                { "diff_very_easy", "Very Easy (Soil)" },
                { "diff_easy", "Easy (Cavern)" },
                { "diff_medium", "Medium (Deep Cavern)" },
                { "diff_hard", "Hard (Abyss)" },
                { "diff_very_hard", "Very Hard (Core)" },
                { "go_title", "YOU DIED" },
                { "go_depth", "Depth Reached: {0}m" },
                { "go_will_earned", "Will Gathered: +{0}" },
                { "go_total_will", "Total Will: {0}" },
                { "go_upgrade_power", "Mining Power: Lv.{0}" },
                { "go_upgrade_hp", "Max HP: Lv.{0}" },
                { "go_upgrade_attack", "Attack Power: Lv.{0}" },
                { "go_will_cost", "{0} Will" },
                { "go_upgrade_btn", "UPGRADE" },
                { "go_restart_btn", "MAIN MENU" },
                { "combat_monster_encounter", "Monster Encountered!" },
                { "combat_monster_encounter_fmt", "{0} Appeared!" },
                { "combat_lava", "LAVA! -{0} HP" },
                { "combat_water", "WATER LOG! -{0} HP" },
                { "combat_miss", "MISS" },
                { "curse_tag", " (CURSE!)" },
                { "lang_toggle", "KO" }, // Clicking in EN toggles to KO
                { "hud_settings_btn", "SETTINGS" },
                { "settings_title", "SETTINGS" },
                { "settings_close", "CLOSE" },
                { "settings_lang_label", "Language" },
                { "go_best_depth", "Best Depth: {0}m" },
                
                // Menu translations
                { "menu_title", "DEEP EARTH" },
                { "menu_play", "PLAY" },
                { "menu_upgrade", "UPGRADES" },
                { "menu_shop", "SHOP" },
                { "menu_settings", "SETTINGS" },
                { "menu_back", "BACK" },
                { "menu_shop_coming_soon", "SHOP COMING SOON!" },
                { "menu_will", "Will: {0}" },
                { "menu_gold_topright", "Gold: {0}" },
                { "menu_upgrade_power", "Mining Power: Lv.{0}" },
                { "menu_upgrade_hp", "Max HP: Lv.{0}" },
                { "menu_upgrade_attack", "Attack Power: Lv.{0}" },
                { "menu_upgrade_inventory", "Bag Capacity: Lv.{0}" },
                { "go_upgrade_inventory", "Bag Capacity: Lv.{0}" },
                
                // Character popup English keys
                { "char_popup_title", "Character Select" },
                { "char_select", "Select" },
                { "char_selected", "Selected" },
                { "char_unlock", "Unlock" },
                { "char_locked", "Locked" },
                { "char_cost_label", "Cost:" },
                { "char_owned_resources", "Owned Resources:" },
                { "char_btn_open", "CHARACTER" },
                { "achievement_btn_open", "ACHIEVEMENTS" },
                { "achievement_popup_title", "Achievements" },
                { "achievement_unlocked_header", "Achievement Unlocked!" },
                { "achievement_completed_label", "Completed" },
                { "achievement_hidden_name", "???" },
                { "achievement_hidden_desc", "Complete to reveal." },

                { "char_prisoner_name", "Prisoner" },
                { "char_prisoner_desc", "Starting point of all growth. No special passive ability." },
                { "char_mercenary_name", "Mercenary" },
                { "char_mercenary_desc", "Specialized in combat.\nPassive: Attack Power +1 (up to +5)" },
                { "char_miner_name", "Miner" },
                { "char_miner_desc", "Specialized in block breaking.\nPassive: Mining Power +1 (up to +5)" },
                { "char_graverobber_name", "Grave Robber" },
                { "char_graverobber_desc", "Specialized in rare resource farming.\nPassive: 10% chance to yield +10% extra Iron/Silver/Gold/Diamond (min +1)." },
                { "char_prisoner_flavor",    "Starting point of all growth." },
                { "char_mercenary_flavor",   "Specialized in combat." },
                { "char_miner_flavor",       "Specialized in block breaking." },
                { "char_graverobber_flavor", "Specialized in rare resource farming." },
                { "run_setup_passive_label", "Passive" },
                { "run_setup_passive_level_fmt", "Lv.{0} / {1}" },

                // Event titles
                { "event_chest_title", "Treasure Chest" },
                { "event_tomb_title", "Ancient Tombstone" },
                { "event_chest_desc", "You discovered an old miner's supply chest! Select one upgrade:" },
                { "event_tomb_desc", "An eerie tombstone lies in the darkness. Reading its runes offers powerful buffs, but comes with a heavy curse..." },
                
                // Buffs & Curses Choice Options
                { "event_opt_mining_title", "Mining Gear Upgrade" },
                { "event_opt_mining_desc", "Increases Attack Damage (+1)" },
                { "event_opt_hp_title", "Heart Crystal" },
                { "event_opt_hp_desc", "Increases Maximum HP (+2)" },
                { "event_opt_inv_title", "Expanded Inventory" },
                { "event_opt_inv_desc", "Increases Inventory Capacity (+5)" },
                { "event_opt_stealth_title", "Stealth Cloak" },
                { "event_opt_stealth_desc", "Decreases Monster Encounter Rate (-15%)" },
                { "event_opt_hat_title", "Hard Hat" },
                { "event_opt_hat_desc", "Decreases Trap/Hazard Encounter Rate (-15%)" },
                { "event_opt_demonic_title", "Demonic Power" },
                { "event_opt_demonic_desc", "Significantly increase Attack Damage (+2)\nCurse: Decreases Max HP (-2)" },
                { "event_opt_greed_title", "Greed Pact" },
                { "event_opt_greed_desc", "Significantly increase Inventory Capacity (+10)\nCurse: Increases Monster Encounter Rate (+25%)" },
                { "event_opt_fortitude_title", "Forbidden Fortitude" },
                { "event_opt_fortitude_desc", "Increase Max HP (+4)\nCurse: Takes damage (-1 HP) on monster encounter" },
                { "event_opt_reckless_title", "Reckless Strike" },
                { "event_opt_reckless_desc", "Significantly increase Attack Damage (+2)\nCurse: 15% chance for mining swings to fail" },
                { "event_opt_vampiric_title", "Vampiric Eye" },
                { "event_opt_vampiric_desc", "Increase Attack Damage (+2)\nCurse: Takes damage (-1 HP) immediately on encountering a monster" },

                // Boss Translations
                { "boss_title", "BOSS" },
                { "boss_rat_name", "Giant Cave Rat" },
                { "boss_spider_name", "Queen Spider" },
                { "boss_golem_name", "Rock Golem" },
                { "boss_worm_name", "Lava Worm" },
                { "boss_titan_name", "Crystal Titan" },
                { "boss_stone_golem_name", "Stone Golem" },
                { "boss_mother_cave_spider_name", "Mother Cave Spider" },
                { "boss_skeleton_warlord_name", "Skeleton Warlord" },
                { "boss_all_metal_colossus_name", "All Metal Colossus" },
                { "boss_reward_title", "BOSS DEFEATED" },
                { "boss_reward_subtitle", "Select one powerful run-local buff:" },
                { "boss_buff_atk", "Attack Power +2" },
                { "boss_buff_atk_desc", "Increases attack power by +2 for the rest of this run." },
                { "boss_buff_hp", "Max HP +5" },
                { "boss_buff_hp_desc", "Increases maximum HP by +5 and heals 5 HP for this run." },
                { "boss_buff_mining", "Mining Power +2" },
                { "boss_buff_mining_desc", "Increases mining power by +2 for the rest of this run." },
                { "boss_buff_mineral", "Mineral Gain +20%" },
                { "boss_buff_mineral_desc", "Increases all resource yields by +20% for this run." },
                { "boss_buff_spawn", "Encounters -20%" },
                { "boss_buff_spawn_desc", "Decreases normal monster encounter probability by -20% for this run." },
                { "boss_fixed_heal_hp", "HP Recovery" },
                { "boss_fixed_heal_hp_desc", "Restore 30% of your maximum HP." },
                { "boss_buff_heal", "Heal Drops +15%" },
                { "boss_buff_heal_desc", "Increases healing item drop rate from monsters by +15% for this run." },
                { "boss_rare_revive", "Legendary Resurrection" },
                { "boss_rare_revive_desc", "Upon death, revive once with 50% HP (Rare)." },
                { "boss_rare_boss_dmg", "Boss Slayer" },
                { "boss_rare_boss_dmg_desc", "Deals +50% extra damage to Bosses (Rare)." },
                { "boss_rare_mineral_50", "Miner's Fortune" },
                { "boss_rare_mineral_50_desc", "Increases all resource yields by +50% for this run (Rare)." },
                { "boss_rare_event_double", "Double Blessing" },
                { "boss_rare_event_double_desc", "All event choice buffs are applied twice (Rare)." },
                { "boss_rare_immortality_potion", "Potion of Immortality" },
                { "boss_rare_immortality_potion_desc", "Grants a Potion of Immortality (Rare)." },
                
                // Effect System
                { "hud_relic_btn", "RELIC" },
                { "hud_inventory_btn", "BAG" },
                { "relic_popup_title", "RELICS & EFFECTS" },
                { "inventory_popup_title", "INVENTORY DETAILS" },
                { "relic_popup_type_label", "Type: {0}" },
                { "relic_popup_effect_label", "Effect: {0}" },

                // Inventory System
                { "hud_quantity_label", "Quantity:" },
                { "hud_hp_heal", "HP Healed!" },
                { "inv_confirm_drop_title", "Really drop?" },
                { "inv_confirm_discard_all_title", "Discard all?" },
                { "inv_confirm_yes", "Confirm" },
                { "inv_confirm_no", "Cancel" },
                { "inv_empty_message", "No items in inventory." },
                { "inv_dropped_fmt", "Dropped {0}" },
                { "item_used_generic_fmt", "Used {0}" },
                { "chest_reward_result_fmt", "+{0} HP, {1}" },
                { "chest_reward_iron_fmt", "+{0} Iron" },
                { "chest_reward_silver_fmt", "+{0} Silver" },
                { "chest_reward_anvil_fmt", "+{0} Portable Anvil" },
                { "chest_reward_gold_fmt", "+{0} Gold" },
                { "map_title", "MAP" },
                { "passive_max_level", "MAX" },
                { "passive_not_upgraded", "Not upgraded" },
                { "status_burn_applied_msg", "Burned!" },
                { "upgrade_passive_btn", "Upgrade" },
                { "item_stone_name", "Stone" },
                { "item_stone_desc", "A heavy piece of stone." },
                { "item_wood_name", "Root" },
                { "item_wood_desc", "A medicinal root. Restores 1 HP when used." },
                { "item_iron_name", "Iron" },
                { "item_iron_desc", "Cold iron ore. Used for equipment crafting." },
                { "item_silver_name", "Silver" },
                { "item_silver_desc", "Shining silver ore." },
                { "item_gold_name", "Gold" },
                { "item_gold_desc", "Glittering gold ore." },
                { "item_diamond_name", "Diamond" },
                { "item_diamond_desc", "Brilliant diamond gem." },
                { "item_potion_name", "Health Potion" },
                { "item_potion_desc", "Restores 5 HP." },
                { "item_potion_medium_name", "Health Potion (Medium)" },
                { "item_potion_medium_desc", "Restores 10 HP." },
                { "item_potion_large_name", "Health Potion (Large)" },
                { "item_potion_large_desc", "Restores 20 HP." },
                { "item_burn_cure_name", "Burn Cure" },
                { "item_burn_cure_desc", "Cures Burn immediately." },
                { "item_burn_cure_used", "Burn cured!" },
                { "item_burn_cure_no_burn", "You are not burned." },
                { "item_key_name", "Chest Key" },
                { "item_key_desc", "Looks like it can open locked chests." },
                { "item_chest_name", "Treasure Box" },
                { "item_chest_desc", "Contains random rewards." },
                { "item_special_name", "Elixir" },
                { "item_special_desc", "A special elixir with mysterious energy. Restores 10 HP." },
                
                { "effect_type_CharacterPassive", "CharacterPassive" },
                { "effect_type_BossReward", "BossReward" },
                { "effect_type_Buff", "Buff" },
                { "effect_type_Debuff", "Debuff" },
                { "effect_type_Special", "Special" },
                
                { "effect_passive_miner_desc", "Mining Power +1" },
                { "effect_passive_mercenary_desc", "Attack Power +1" },
                { "effect_passive_miner_value_fmt", "Mining Power +{0}" },
                { "effect_passive_mercenary_value_fmt", "Attack Power +{0}" },
                { "effect_passive_graverobber_desc", "10% chance for +10% extra resource" },
                
                { "effect_buff_attack_name", "Attack Power Up" },
                { "effect_buff_attack_desc", "Attack Power +{0}" },
                { "effect_buff_maxhp_name", "Max HP Up" },
                { "effect_buff_maxhp_desc", "Maximum HP +{0}" },
                { "effect_buff_inventory_name", "Bag Expansion" },
                { "effect_buff_inventory_desc", "Inventory Capacity +{0}" },
                { "effect_buff_monsterspawn_name", "Safe Zone" },
                { "effect_buff_monsterspawn_desc", "Monster Spawn Rate -{0}%" },
                { "effect_buff_hazardspawn_name", "Hazard Safety" },
                { "effect_buff_hazardspawn_desc", "Trap Spawn Rate -{0}%" },
                
                { "effect_curse_attack_name", "Weakness Curse" },
                { "effect_curse_attack_desc", "Attack Power -{0}" },
                { "effect_curse_maxhp_name", "Decay Curse" },
                { "effect_curse_maxhp_desc", "Maximum HP -{0}" },
                { "effect_curse_monsterspawn_name", "Ominous Sign" },
                { "effect_curse_monsterspawn_desc", "Monster Spawn Rate +{0}%" },
                { "effect_curse_hazardspawn_name", "Calamity Curse" },
                { "effect_curse_hazardspawn_desc", "Trap Spawn Rate +{0}%" },
                { "effect_curse_instantdamage_name", "Blood Spill" },
                { "effect_curse_instantdamage_desc", "Takes -{0} HP instantly on monster encounter" },
                { "effect_curse_miningfail_name", "Broken Gear" },
                { "effect_curse_miningfail_desc", "Mining Swing Fail Chance +{0}%" },
                
                { "effect_boss_attack_name", "Cave Rat Slayer" },
                { "effect_boss_attack_desc", "Attack Power +2" },
                { "effect_boss_maxhp_name", "Boss Fortitude" },
                { "effect_boss_maxhp_desc", "Maximum HP +5" },
                { "effect_boss_mining_name", "Destroyer" },
                { "effect_boss_mining_desc", "Mining Power +2" },
                { "effect_boss_mineral20_name", "Greed Symbol" },
                { "effect_boss_mineral20_desc", "Mineral Yield +20%" },
                { "effect_boss_spawndecrease_name", "Stealth" },
                { "effect_boss_spawndecrease_desc", "Monster Spawn Rate -20%" },
                { "effect_boss_healdrop_name", "Life Essence" },
                { "effect_boss_healdrop_desc", "Monster Heal Drop Chance +15%" },
                { "effect_boss_revive_name", "Phoenix Feather" },
                { "effect_boss_revive_desc", "Revive 1 time with 100% HP" },
                { "effect_boss_bossdamage_name", "Giant Hunter" },
                { "effect_boss_bossdamage_desc", "Damage to Bosses +50%" },
                { "effect_boss_mineral50_name", "Millionaire" },
                { "effect_boss_mineral50_desc", "Mineral Yield +50%" },
                { "effect_boss_doubleevent_name", "Double Blessing" },
                { "effect_boss_doubleevent_desc", "Doubles event buff effects" },
                { "effect_boss_immortality_potion_name", "Potion of Immortality" },
                { "effect_boss_immortality_potion_desc", "Granted a Potion of Immortality" },

                { "item_portable_anvil_name", "Portable Anvil" },
                { "item_portable_anvil_desc", "A small portable anvil. Instantly restores 5 pickaxe durability when used." },
                { "item_immortality_potion_name", "Potion of Immortality" },
                { "item_immortality_potion_desc", "Automatically consumed at the moment of death. Activates once, reviving you with 5 HP." },
                { "item_anvil_full", "Durability is already at maximum." },
                { "item_auto_use", "Auto-Use" },
                { "item_poison_cure_used", "Poison cured!" },
                { "item_poison_cure_no_poison", "You are not poisoned." },
                { "item_combat_only", "Can only be used during combat." },

                { "item_repair_kit_name", "Repair Kit" },
                { "item_repair_kit_desc", "Instantly restores 3 pickaxe durability when used." },
                { "item_antidote_potion_name", "Antidote" },
                { "item_antidote_potion_desc", "Cures Poison immediately." },
                { "item_bomb_name", "Bomb" },
                { "item_bomb_desc", "Deals 5 damage to all monsters in combat. Usable only during combat." },
                { "item_holy_water_name", "Holy Water" },
                { "item_holy_water_desc", "Cures Burn and Poison immediately." },
                { "item_enhanced_repair_kit_name", "Enhanced Repair Kit" },
                { "item_enhanced_repair_kit_desc", "Instantly restores 10 pickaxe durability when used." },
                { "item_enhanced_bomb_name", "Enhanced Bomb" },
                { "item_enhanced_bomb_desc", "Deals 15 damage to all monsters in combat. Usable only during combat." },
                { "item_angel_feather_name", "Angel Feather" },
                { "item_angel_feather_desc", "Fully restores HP and cures Burn and Poison." },
                { "item_full_repair_kit_name", "Full Repair Kit" },
                { "item_full_repair_kit_desc", "Fully restores pickaxe durability when used." },
                { "item_guardian_heart_name", "Guardian's Heart" },
                { "item_guardian_heart_desc", "Automatically consumed at the moment of death. Activates once, reviving you with 15 HP." },

                { "merchant_title", "Wandering Merchant" },
                { "merchant_leave_button", "Leave" },
                { "merchant_sold_out", "SOLD OUT" },
                { "merchant_relic_section_label", "Relics" },
                { "merchant_consumable_section_label", "Consumables" },
                { "merchant_potion_section_label", "Potions" },
                { "merchant_featured_label", "Today's Pick" },
                { "merchant_discount_banner_all_fmt", "{0}% off everything today!" },
                { "merchant_discount_banner_relic_fmt", "{0}% off Rare relics today!" },
                { "merchant_hp_full", "HP is already full." },
                { "merchant_currency_fmt", "Silver {0}  Gold {1}  Diamond {2}  Root {3}" },

                { "battle_player_turn", "Player Turn" },
                { "battle_monster_turn", "Enemy Turn" },
                { "intent_attack_desc", "Attack" },
                { "intent_heavy_attack_desc", "Heavy Attack" },
                { "intent_defend_desc", "Defend" },
                { "intent_buff_desc", "Buff" },
                { "intent_debuff_desc", "Debuff" },
                { "intent_heal_desc", "Heal" },
                { "intent_summon_desc", "Summon" },
                { "intent_special_desc", "Special" },

                { "merchant_quote_01", "Still alive, I see." },
                { "merchant_quote_02", "The deeper you go, the better the goods." },
                { "merchant_quote_03", "Nothing costs more than your life." },
                { "merchant_quote_04", "A relic chooses its own owner." },
                { "merchant_quote_05", "Take a look. Everything here has a story." },
                { "merchant_quote_06", "I only deal in things worth dying for." },
                { "merchant_quote_07", "Careful — some of these bite back." },
                { "merchant_quote_08", "You won't find this anywhere else in the mine." },
                { "merchant_quote_09", "Gold spends the same down here as anywhere." },
                { "merchant_quote_10", "I've buried better customers than you." },
                { "merchant_quote_11", "Every item has its price. Even the cheap ones." },
                { "merchant_quote_12", "Don't dawdle. The dark doesn't wait." },
                { "merchant_quote_13", "I've seen fortunes made and lost on relics like these." },
                { "merchant_quote_14", "A wise miner spends before the depths take it anyway." },
                { "merchant_quote_15", "Feeling lucky today?" },
                { "merchant_quote_16", "That one's cursed. Probably." },
                { "merchant_quote_17", "I travel where the desperate go." },
                { "merchant_quote_18", "You'll thank me later. Or not at all." },
                { "merchant_quote_19", "Business is good when the mine is dangerous." },
                { "merchant_quote_20", "Buy now, regret never." },
                { "merchant_quote_21", "I don't ask where the gold comes from." },
                { "merchant_quote_22", "There's always a customer who comes back for more." },
                { "merchant_quote_23", "Some come for potions. Some come for hope." },
                { "merchant_quote_24", "Every relic I sell has killed at least one owner." },
                { "merchant_quote_legendary_relic", "Now THAT is a find worth remembering." },
                { "merchant_quote_legendary_item", "You won't see something like that twice in a lifetime." },
                { "merchant_quote_no_funds", "Come back when you've got the coin." },

                { "hud_pickaxe_broken", "Broken" },
                { "pickaxe_broken_alert_title", "Pickaxe is broken!" },
                { "pickaxe_broken_alert_desc", "Mining will now consume HP." },
                { "pickaxe_repair_full", "Durability is already full!" },
                { "pickaxe_repair_not_enough", "Not enough materials!" },

                // Achievement names / descs
                { "ach_first_step_name", "First Step" },
                { "ach_first_step_desc", "Start your first run." },
                { "ach_depth50_name", "Fifty Fathoms" },
                { "ach_depth50_desc", "Reach depth 50." },
                { "ach_depth100_name", "Deep Dive" },
                { "ach_depth100_desc", "Reach depth 100." },
                { "ach_depth200_name", "The Abyss" },
                { "ach_depth200_desc", "Reach depth 200." },
                { "ach_kill10_name", "Monster Slayer" },
                { "ach_kill10_desc", "Defeat 10 monsters." },
                { "ach_kill50_name", "Exterminator" },
                { "ach_kill50_desc", "Defeat 50 monsters." },
                { "ach_boss_first_name", "First Blood" },
                { "ach_boss_first_desc", "Defeat your first boss." },
                { "ach_boss_cave_rat_name", "Rat Catcher" },
                { "ach_boss_cave_rat_desc", "Defeat the Cave Rat boss." },
                { "ach_ore_iron50_name", "Iron Will" },
                { "ach_ore_iron50_desc", "Mine 50 iron ore." },
                { "ach_ore_diamond10_name", "Diamond Hunter" },
                { "ach_ore_diamond10_desc", "Mine 10 diamond ore." },
                { "ach_relic1_name", "Collector" },
                { "ach_relic1_desc", "Collect your first relic." },
                { "ach_relic5_name", "Hoarder" },
                { "ach_relic5_desc", "Collect 5 relics." },
                { "ach_death1_name", "It Hurts" },
                { "ach_death1_desc", "Die for the first time." },
                { "ach_repair1_name", "Handyman" },
                { "ach_repair1_desc", "Repair your pickaxe once." },
                { "ach_lava1_name", "Playing with Fire" },
                { "ach_lava1_desc", "Survive a lava encounter." },
                { "ach_treasure5_name", "Treasure Hunter" },
                { "ach_treasure5_desc", "Open 5 treasure chests." },

                { "effect_type_StatusEffect", "Status Effect" },

                { "status_burn_name", "Burn" },
                { "status_burn_desc", "Takes burn damage each action turn" },

                { "status_mining_down_name", "Mining Power Down" },
                { "status_mining_down_desc", "Mining power is reduced for a few turns." },
                { "status_mining_up_name", "Mining Power Up" },
                { "status_mining_up_desc", "Mining power is boosted for a few turns." },

                { "reveal_monster_slime", "Slime Appears!" },
                { "monster_slime_name", "Slime" },
                { "monster_small_slime_name", "Small Slime" },
                { "monster_skeleton_name", "Skeleton" },
                { "monster_armored_skeleton_name", "Armored Skeleton" },
                { "monster_mimic_name", "Mimic" },

                { "relic_heat_resistant_charm_name", "Heat Resistant Charm" },
                { "relic_heat_resistant_charm_desc", "Burn duration -3 turns" },
                { "relic_frozen_crystal_name", "Frozen Crystal" },
                { "relic_frozen_crystal_desc", "Burn damage -1" },
                { "relic_firefighter_helmet_name", "Firefighter Helmet" },
                { "relic_firefighter_helmet_desc", "Burn duration -2 turns, damage -1" },
                { "relic_purification_ring_name", "Purification Ring" },
                { "relic_purification_ring_desc", "50% chance to negate Burn" },
                { "relic_burning_heart_name", "Burning Heart" },
                { "relic_burning_heart_desc", "Attack +2, Burn duration +3 turns" },
                { "relic_lava_contract_name", "Lava Contract" },
                { "relic_lava_contract_desc", "Resource +25%, Burn damage +1" },
                { "relic_cursed_ash_name", "Cursed Ash" },
                { "relic_cursed_ash_desc", "Max HP +5, Burn duration +5 turns" },
                { "relic_fire_cult_mask_name", "Fire Cult Mask" },
                { "relic_fire_cult_mask_desc", "Monster Attack +2, Burn damage +2" },

                // Shop tabs
                { "shop_tab_pickaxe",    "Pickaxe" },
                { "shop_tab_character",  "Character" },
                { "shop_tab_consumable", "Item" },
                { "shop_tab_special",    "Special" },
                { "shop_owned",          "OWNED" },
                { "shop_info_select",    "Select an item" },

                // Pickaxe Shop
                { "shop_pickaxe_title",        "Pickaxes" },
                { "shop_pickaxe_mining_power", "⛏ Mining Power: {0}" },
                { "shop_pickaxe_durability",   "♦ Max Durability: {0}" },
                { "shop_pickaxe_buy",          "BUY" },
                { "shop_pickaxe_equip",        "EQUIP" },
                { "shop_pickaxe_equipped",     "EQUIPPED" },

                { "pickaxe_wood_name",    "Wood Pickaxe" },
                { "pickaxe_wood_desc",    "A basic pickaxe. Reliable but weak." },
                { "pickaxe_iron_name",    "Iron Pickaxe" },
                { "pickaxe_iron_desc",    "Forged from iron. Breaks ore faster." },
                { "pickaxe_silver_name",  "Silver Pickaxe" },
                { "pickaxe_silver_desc",  "A refined pickaxe. Cuts through stone with ease." },
                { "pickaxe_gold_name",    "Gold Pickaxe" },
                { "pickaxe_gold_desc",    "A heavy pickaxe of great power." },
                { "pickaxe_diamond_name", "Diamond Pickaxe" },
                { "pickaxe_diamond_desc", "The ultimate pickaxe. Nothing can stop it." },

                // Mining Power buff/curse effects
                { "effect_buff_mining_name", "Mining Power Up" },
                { "effect_buff_mining_desc", "Mining Power +{0}" },
                { "effect_curse_mining_name", "Mining Curse" },
                { "effect_curse_mining_desc", "Mining Power -{0}" },

                // New Treasure Relics - Mining
                { "relic_miners_gloves_name", "Miner's Gloves" },
                { "relic_miners_gloves_desc", "Mining Power +1" },
                { "relic_mining_king_helmet_name", "Mining King's Helmet" },
                { "relic_mining_king_helmet_desc", "Mining Power +2" },
                { "relic_broken_drill_name", "Broken Drill" },
                { "relic_broken_drill_desc", "Mining Power +3, Max HP -5" },
                { "relic_ore_detector_name", "Ore Detector" },
                { "relic_ore_detector_desc", "Mining Power +1, Resource Yield +20%" },

                // New Treasure Relics - Combat
                { "relic_warriors_ring_name", "Warrior's Ring" },
                { "relic_warriors_ring_desc", "Attack Power +1" },
                { "relic_mercenary_medal_name", "Mercenary's Medal" },
                { "relic_mercenary_medal_desc", "Attack Power +2" },
                { "relic_blood_contract_name", "Blood Contract" },
                { "relic_blood_contract_desc", "Attack Power +3, Max HP -5" },
                { "relic_hunters_eye_name", "Hunter's Eye" },
                { "relic_hunters_eye_desc", "Attack Power +1, Pickaxe Durability -2" },

                // New Tombstone Relics
                { "relic_cursed_pickaxe_name", "Cursed Pickaxe" },
                { "relic_cursed_pickaxe_desc", "Mining Power +2, Burn Damage +1" },
                { "relic_madness_sword_name", "Blade of Madness" },
                { "relic_madness_sword_desc", "Attack Power +2, Pickaxe Durability -3" },
                { "relic_cursed_mining_gloves_name", "Cursed Mining Gloves" },
                { "relic_cursed_mining_gloves_desc", "Mining Power +1, Max HP -3" },
                { "relic_blood_rune_name", "Blood Rune" },
                { "relic_blood_rune_desc", "Attack Power +1, Burn Duration +2 turns" },

                // Run Setup
                { "run_setup_title",  "Run Setup" },
                { "run_setup_start",  "Start Run!" },
                { "run_setup_char_label",    "CHARACTER" },
                { "run_setup_pickaxe_label", "PICKAXE" },

                // Loading steps
                { "loading_init",               "Initializing..." },
                { "loading_assets",             "Loading assets..." },
                { "loading_save",               "Loading save data..." },
                { "loading_preparing",          "Preparing..." },
                { "loading_ready",              "Ready!" },
                { "loading_step_playerdata",    "Loading player data..." },
                { "loading_step_rundata",       "Preparing run..." },
                { "loading_step_character",     "Applying character..." },
                { "loading_step_pickaxe",       "Equipping pickaxe..." },
                { "loading_step_items",         "Preparing starting items..." },
                { "loading_step_passive",       "Applying passives..." },
                { "loading_step_stats",         "Calculating stats..." },
                { "loading_step_runreset",      "Initializing run state..." },
                { "loading_step_assets",        "Loading assets..." },
                { "loading_step_pools",         "Setting up pools..." },
                { "loading_step_locale",        "Loading localization..." },
                { "loading_step_sound",         "Loading sounds..." },
                { "loading_step_verify",        "Verifying data..." },
                { "loading_step_enter",         "Entering the mine..." },
                { "loading_tip_cave",           "The deeper you go, the stronger the monsters..." },

                // Exit Run
                { "exit_run_btn",         "Give Up Run" },
                { "exit_run_confirm_msg", "Are you sure you want to give up this run?\nAll current run progress will be lost." },
                { "exit_run_cancel_btn",  "Cancel" },
                { "exit_run_confirm_btn", "Give Up Run" },

                // Node Events — common
                { "event_btn_continue",              "Continue" },
                { "event_btn_continue_desc",         "Acknowledge and move on." },

                // Node Events — Negative
                { "event_rockfall_title",            "Rockfall!" },
                { "event_rockfall_desc",             "The ceiling crumbles. Dodge or take the hit?" },
                { "event_rockfall_dodge_title",      "① Dodge (Turn +2)" },
                { "event_rockfall_dodge_desc",       "Spend 2 extra turns navigating around the rubble." },
                { "event_rockfall_hit_title",        "② Take the hit (HP-2, Iron×2)" },
                { "event_rockfall_hit_desc",         "Endure the blow and recover what ore fell from above." },
                { "event_rockfall_dodge",            "You carefully dodged the rubble." },

                { "event_poisonmist_title",          "Poison Mist" },
                { "event_poisonmist_desc",           "A toxic cloud seeps from the cracks. Act fast!" },
                { "event_poisonmist_inhale_title",   "① Inhale (Attack -10%, 6 turns)" },
                { "event_poisonmist_inhale_desc",    "Breathing the mist weakens your attacks for 6 turns." },
                { "event_poisonmist_rush_title",     "② Rush through (spend 5 minerals)" },
                { "event_poisonmist_rush_desc",      "Throw minerals as a distraction and sprint past (Diamond > Gold > Silver > Iron)." },

                { "event_spiketrap_title",           "Spike Trap!" },
                { "event_spiketrap_desc",            "A hidden trap springs beneath you!" },
                { "event_spiketrap_detour_title",    "① Detour (Turn +3)" },
                { "event_spiketrap_detour_desc",     "Take a long route around. Costs 3 turns." },
                { "event_spiketrap_dash_title",      "② Dash through (70% safe / 30% HP-3)" },
                { "event_spiketrap_dash_desc",       "Sprint across the trap. 30% chance of taking 3 damage." },
                { "event_trap_detour",               "You took the long way around." },
                { "event_trap_safe",                 "You made it through unscathed!" },

                { "event_collapsedtunnel_title",     "Collapsed Tunnel" },
                { "event_collapsedtunnel_desc",      "The path ahead has caved in! Your pickaxe scrapes through, but takes heavy damage. The next path node is bypassed." },

                { "event_darkaltar_title",           "Dark Altar" },
                { "event_darkaltar_desc",            "A sinister altar pulsates with dark energy. Will you offer your blood?" },
                { "event_darkaltar_offer_title",     "① Offer blood (HP-5, random relic)" },
                { "event_darkaltar_offer_desc",      "Sacrifice 5 HP to receive a random relic from the shadows." },
                { "event_darkaltar_skip_title",      "② Pass by" },
                { "event_darkaltar_skip_desc",       "Ignore the altar and continue your descent." },

                { "event_lostspirit_title",          "Lost Spirit" },
                { "event_lostspirit_desc",           "A wandering spirit blocks your way, demanding tribute." },
                { "event_lostspirit_appease_title",  "① Appease (spend 5 minerals, random buff)" },
                { "event_lostspirit_appease_desc",   "Offer minerals to calm the spirit. Receive a random power boost." },
                { "event_lostspirit_ignore_title",   "② Ignore (next monster Attack+1)" },
                { "event_lostspirit_ignore_desc",    "Push past. The spirit curses your next encounter." },
                { "event_spirit_appeased",           "The spirit departs, leaving a boon." },
                { "event_spirit_angered",            "The spirit's curse lingers..." },

                // Node Events — Positive
                { "event_camp_title",                "Abandoned Camp" },
                { "event_camp_desc",                 "An old miner's camp! Rest here to recover your strength." },

                { "event_richore_title",             "Rich Ore Vein" },
                { "event_richore_desc",              "A glittering vein stretches before you. How deep will you mine?" },
                { "event_richore_normal_title",      "① Normal mining (Iron×3, Silver×2, Gold×1)" },
                { "event_richore_normal_desc",       "Gather at a safe pace." },
                { "event_richore_intense_title",     "② Intensive mining (×3 ore, 20% elite encounter)" },
                { "event_richore_intense_desc",      "Strip the vein bare — but the noise may attract an elite monster." },
                { "event_rich_ore_elite",            "The noise attracted something..." },


                { "event_hotspring_title",           "Hot Spring" },
                { "event_hotspring_desc",            "Steam rises from a hidden hot spring. Soak in its healing waters." },

                { "event_equipment_title",           "Abandoned Equipment" },
                { "event_equipment_desc",            "A pile of old gear left behind by a miner. Something useful might be salvageable." },

                { "event_journal_title",             "Miner's Journal" },
                { "event_journal_desc",              "A worn journal filled with notes on rich ore seams. Reading it gives you insight for the next 20 nodes." },

                { "event_shrine_title",              "Crystal Shrine" },
                { "event_shrine_desc",               "A shrine of glowing crystals. Its power flows into you — choose your blessing." },
                { "event_shrine_atk",                "① Attack Blessing (Attack+1)" },
                { "event_shrine_atk_desc",           "The crystals sharpen your combat instincts." },
                { "event_shrine_mining",             "② Mining Blessing (Mining+1)" },
                { "event_shrine_mining_desc",        "The crystals guide your pickaxe strikes." },
                { "event_shrine_hp",                 "③ Vitality Blessing (Max HP+2)" },
                { "event_shrine_hp_desc",            "The crystals fortify your body." },
                { "event_shrine_spawn",              "④ Ward Blessing (Monster Rate-15%)" },
                { "event_shrine_spawn_desc",         "The crystals cloak you from monsters." },

                { "event_merchant_no_funds",         "Not enough materials!" },

                { "event_forge_title",               "Ancient Forge" },
                { "event_forge_desc",                "A still-burning forge from a long-dead civilization. Will you use it?" },
                { "event_forge_atk_title",           "① Forge weapon edge (Attack+1 / 5×Gold)" },
                { "event_forge_atk_desc",            "Temper your weapon on the ancient anvil." },
                { "event_forge_mining_title",        "② Reinforce pickaxe head (Mining+1 / 5×Iron)" },
                { "event_forge_mining_desc",         "Strengthen your pickaxe with raw iron." },
                { "event_forge_heal_title",          "③ Craft ration (HP+5 / 3×Silver)" },
                { "event_forge_heal_desc",           "Smelt silver into a restorative meal." },
                { "event_forge_skip_title",          "④ Leave" },
                { "event_forge_skip_desc",           "The heat is too intense. Move on." },

                // Node Events — Risk/Reward
                { "event_devil_title",               "Devil's Contract" },
                { "event_devil_desc",                "A shadowy figure offers power... at a price." },
                { "event_devil_atk_title",           "① Attack contract (HP-20%, Attack+2)" },
                { "event_devil_atk_desc",            "Trade 20% of your max HP for a permanent +2 attack boost." },
                { "event_devil_mining_title",        "② Mining contract (HP-20%, Mining+2)" },
                { "event_devil_mining_desc",         "Trade 20% of your max HP for a permanent +2 mining boost." },
                { "event_devil_skip_title",          "③ Refuse" },
                { "event_devil_skip_desc",           "Walk away from the deal." },

                { "event_minegod_title",             "Mine God's Blessing" },
                { "event_minegod_desc",              "The ancient god of the deep regards you with favor. Choose one blessing." },
                { "event_minegod_atk_title",         "① Attack Blessing (Attack+1)" },
                { "event_minegod_atk_desc",          "The god sharpens your blade." },
                { "event_minegod_mining_title",      "② Mining Blessing (Mining+1)" },
                { "event_minegod_mining_desc",       "The god empowers your pickaxe." },
                { "event_minegod_hp_title",          "③ Vitality Blessing (Max HP+2)" },
                { "event_minegod_hp_desc",           "The god strengthens your body." },

                // Status: Poison
                { "status_poison_name",              "Poison" },
                { "status_poison_desc",              "Attack power reduced by 10% for the duration." },

                // Ore Gain buff (Miner's Journal)
                { "effect_ore_gain_name",            "Ore Seam Knowledge" },
                { "effect_ore_gain_desc",            "Ore yield +20% for {0} more nodes." },

                // Relic rarity names
                { "relic_rarity_common",    "Common" },
                { "relic_rarity_rare",      "Rare" },
                { "relic_rarity_legendary", "Legendary" },

                // Relic tag names
                { "relic_tag_mining",   "Mining" },
                { "relic_tag_combat",   "Combat" },
                { "relic_tag_defense",  "Defense" },
                { "relic_tag_economy",  "Economy" },
                { "relic_tag_pickaxe",  "Pickaxe" },
                { "relic_tag_healing",  "Healing" },
                { "relic_tag_status",   "Status" },
                { "relic_tag_boss",     "Boss" },
                { "relic_tag_elite",    "Elite" },
                { "relic_tag_utility",  "Utility" },

                // Elite monsters
                { "monster_big_slime_name",       "Big Slime" },
                { "monster_big_slime_desc",       "Splits into 3 Slimes on death." },
                { "monster_skeleton_miner_name",  "Skeleton Miner" },
                { "monster_skeleton_miner_desc",  "Steals minerals from your inventory periodically." },
                { "monster_iron_spider_name",     "Iron Plate Spider" },
                { "monster_iron_spider_desc",     "Protected by iron armor. Poisons every 3 attacks after armor breaks." },
                { "monster_merchant_mimic_name",  "Merchant Mimic" },
                { "monster_merchant_mimic_desc",  "A rare mimic that drops valuable mineral rewards." },
                { "monster_cursed_knight_name",   "Cursed Knight" },
                { "monster_cursed_knight_desc",   "Enrages at 75%, 50%, 25% HP — gains speed and power." },
                { "monster_cursed_priest_name",   "Cursed Priest" },
                { "monster_cursed_priest_desc",   "Weakens your attack power every second. Debuff clears on defeat." },
                { "relic_miner_glove_name", "Miner's Glove" },
                { "relic_miner_glove_desc", "Mining power +1" },
                { "relic_old_whetstone_name", "Old Whetstone" },
                { "relic_old_whetstone_desc", "Attack power +1" },
                { "relic_sturdy_backpack_name", "Sturdy Backpack" },
                { "relic_sturdy_backpack_desc", "Inventory +5 slots" },
                { "relic_emergency_bandage_name", "Emergency Bandage" },
                { "relic_emergency_bandage_desc", "Heal +1 HP after each combat" },
                { "relic_reinforced_handle_name", "Reinforced Handle" },
                { "relic_reinforced_handle_desc", "Pickaxe max durability +10" },
                { "relic_oil_bottle_name", "Oil Bottle" },
                { "relic_oil_bottle_desc", "Pickaxe durability loss -20%" },
                { "relic_iron_ornament_name", "Iron Pickaxe Ornament" },
                { "relic_iron_ornament_desc", "Iron gain +20%" },
                { "relic_silver_necklace_name", "Silver Necklace" },
                { "relic_silver_necklace_desc", "Silver gain +20%" },
                { "relic_gold_pouch_name", "Gold Pouch" },
                { "relic_gold_pouch_desc", "Gold gain +20%" },
                { "relic_diamond_brooch_name", "Diamond Brooch" },
                { "relic_diamond_brooch_desc", "Diamond gain +20%" },
                { "relic_miner_canteen_name", "Miner's Canteen" },
                { "relic_miner_canteen_desc", "Burn duration -2 turns" },
                { "relic_work_glove_name", "Work Glove" },
                { "relic_work_glove_desc", "Mining power +1 when pickaxe durability >= 50%" },
                { "relic_iron_boot_name", "Iron-Nail Boot" },
                { "relic_iron_boot_desc", "Rockfall and Spike Trap damage -1" },
                { "relic_small_whetstone_name", "Small Whetstone" },
                { "relic_small_whetstone_desc", "Damage to Elite Monsters +10%" },
                { "relic_lucky_pickaxe_name", "Lucky Pickaxe" },
                { "relic_lucky_pickaxe_desc", "5% chance to gain an extra ore on each mine" },
                { "relic_miner_lunchbox_name", "Miner's Lunchbox" },
                { "relic_miner_lunchbox_desc", "Heal +5 HP after defeating a Boss" },
                { "relic_leather_handle_name", "Leather Handle" },
                { "relic_leather_handle_desc", "Pickaxe durability loss -10%" },
                { "relic_mining_permit_name", "Mining Permit" },
                { "relic_mining_permit_desc", "20% chance to gain 1 Iron on monster kill" },
                { "relic_auto_repair_kit_name", "Auto Repair Kit" },
                { "relic_auto_repair_kit_desc", "Pickaxe durability +1 on monster kill" },
                { "relic_vampire_pickaxe_name", "Vampire Pickaxe" },
                { "relic_vampire_pickaxe_desc", "10% chance to heal +1 HP on each mine" },
                { "relic_ore_sensor_name", "Ore Sensor" },
                { "relic_ore_sensor_desc", "All ore gain +30%" },
                { "relic_steel_heart_name", "Steel Heart" },
                { "relic_steel_heart_desc", "Max HP +10" },
                { "relic_mine_ring_name", "Mine Ring" },
                { "relic_mine_ring_desc", "Mining power +2" },
                { "relic_warrior_necklace_name", "Warrior's Necklace" },
                { "relic_warrior_necklace_desc", "Attack power +2" },
                { "relic_magma_amulet_name", "Magma Amulet" },
                { "relic_magma_amulet_desc", "Immune to Burn" },
                { "relic_waterproof_boot_name", "Waterproof Boot" },
                { "relic_waterproof_boot_desc", "Immune to Flood damage" },
                { "relic_poison_antidote_name", "Poison Antidote" },
                { "relic_poison_antidote_desc", "Immune to Poison" },
                { "relic_greedy_coin_name", "Greedy Coin" },
                { "relic_greedy_coin_desc", "Ore gain +50%. All HP recovery reduced by 50%." },
                { "relic_cursed_digger_name", "Cursed Digger" },
                { "relic_cursed_digger_desc", "Mining power +3  Max HP -10" },
                { "relic_elite_hunter_medal_name", "Elite Hunter Medal" },
                { "relic_elite_hunter_medal_desc", "Gain an extra relic choice on Elite Monster kill" },
                { "relic_god_pickaxe_name", "God's Pickaxe" },
                { "relic_god_pickaxe_desc", "Mining power +5" },
                { "relic_mine_crown_name", "Mine Crown" },
                { "relic_mine_crown_desc", "All ore yield x2" },
                { "relic_immortal_heart_name", "Immortal Heart" },
                { "relic_immortal_heart_desc", "Revive once per run at 30% HP" },
                { "relic_soul_contract_name", "Soul Contract" },
                { "relic_soul_contract_desc", "Attack power +5  Max HP -20" },
                { "relic_dragon_fang_name", "Dragon Fang" },
                { "relic_dragon_fang_desc", "Damage to all monsters +50%" },
                { "relic_infinite_whetstone_name", "Infinite Whetstone" },
                { "relic_infinite_whetstone_desc", "Pickaxe loses no durability" },
                { "relic_mine_blessing_name", "Mine God's Blessing" },
                { "relic_mine_blessing_desc", "Attack +3  Mining +3  Max HP +3" },
                { "relic_golden_bag_name", "Golden Bag" },
                { "relic_golden_bag_desc", "Iron, Silver, Gold, Diamond gain +50%" },
                { "relic_hourglass_name", "Hourglass of Time" },
                { "relic_hourglass_desc", "Fully restore HP on Boss kill" },
                { "relic_abyssal_core_name", "Abyssal Core" },
                { "relic_abyssal_core_desc", "Elite Monster rewards x2 (spawn rate unchanged)" },
            };

            // Korean translations
            var ko = new Dictionary<string, string>
            {
                { "hud_hp", "체력: {0} / {1}" },
                { "hud_depth", "깊이: {0}m" },
                { "hud_bag", "가방: {0} / {1}" },
                { "hud_iron", "철: {0}" },
                { "hud_silver", "은: {0}" },
                { "hud_gold", "금: {0}" },
                { "hud_diamond", "다이아: {0}" },
                { "hud_inv_full", "가방이 가득 찼습니다!" },
                { "diff_very_easy", "매우 쉬움 (흙)" },
                { "diff_easy", "쉬움 (동굴)" },
                { "diff_medium", "보통 (깊은 동굴)" },
                { "diff_hard", "어려움 (심연)" },
                { "diff_very_hard", "매우 어려움 (지하 핵)" },
                { "go_title", "사망하셨습니다" },
                { "go_depth", "도달한 깊이: {0}m" },
                { "go_will_earned", "획득한 의지: +{0}" },
                { "go_total_will", "보유한 의지: {0}" },
                { "go_upgrade_power", "채굴력: Lv.{0}" },
                { "go_upgrade_hp", "최대 체력: Lv.{0}" },
                { "go_upgrade_attack", "공격력: Lv.{0}" },
                { "go_will_cost", "{0} 의지" },
                { "go_upgrade_btn", "업그레이드" },
                { "go_restart_btn", "메인 메뉴로" },
                { "combat_monster_encounter", "몬스터 출현!" },
                { "combat_monster_encounter_fmt", "{0} 출현!" },
                { "combat_lava", "용암! -{0} 체력" },
                { "combat_water", "침수! -{0} 체력" },
                { "combat_miss", "빗나감" },
                { "curse_tag", " (저주!)" },
                { "lang_toggle", "EN" }, // Clicking in KO toggles to EN
                { "hud_settings_btn", "설정" },
                { "settings_title", "설정" },
                { "settings_close", "종료" },
                { "settings_lang_label", "언어" },
                { "go_best_depth", "최고 깊이: {0}m" },
                
                // Menu translations
                { "menu_title", "디프 어스" },
                { "menu_play", "게임 시작" },
                { "menu_upgrade", "업그레이드" },
                { "menu_shop", "상점" },
                { "menu_settings", "설정" },
                { "menu_back", "뒤로가기" },
                { "menu_shop_coming_soon", "상점 준비 중!" },
                { "menu_will", "보유한 의지: {0}" },
                { "menu_gold_topright", "보유 골드: {0}" },
                { "menu_upgrade_power", "채굴력: Lv.{0}" },
                { "menu_upgrade_hp", "최대 체력: Lv.{0}" },
                { "menu_upgrade_attack", "공격력: Lv.{0}" },
                { "menu_upgrade_inventory", "인벤토리 용량: Lv.{0}" },
                { "go_upgrade_inventory", "인벤토리 용량: Lv.{0}" },
                
                // Character popup Korean keys
                { "char_popup_title", "캐릭터 선택" },
                { "char_select", "선택" },
                { "char_selected", "선택됨" },
                { "char_unlock", "해금" },
                { "char_locked", "잠김" },
                { "char_cost_label", "해금 비용:" },
                { "char_owned_resources", "보유 자원:" },
                { "char_btn_open", "캐릭터" },
                { "achievement_btn_open", "업적" },
                { "achievement_popup_title", "업적" },
                { "achievement_unlocked_header", "업적 달성!" },
                { "achievement_completed_label", "달성" },
                { "achievement_hidden_name", "???" },
                { "achievement_hidden_desc", "달성 시 공개됩니다." },

                { "char_prisoner_name", "죄인" },
                { "char_prisoner_desc", "모든 성장의 시작점. 특별한 고유 능력이 없습니다." },
                { "char_mercenary_name", "용병" },
                { "char_mercenary_desc", "전투에 특화된 캐릭터.\n패시브: 기본 공격력 +1 (최대 +5)" },
                { "char_miner_name", "광부" },
                { "char_miner_desc", "블록 파괴에 특화된 캐릭터.\n패시브: 추가 채굴력 +1 (최대 +5)" },
                { "char_graverobber_name", "도굴꾼" },
                { "char_graverobber_desc", "희귀 자원 수급에 특화된 캐릭터.\n패시브: 철/은/금/다이아 획득 시 10% 확률로 10% 추가 획득 (최소 +1)." },
                { "char_prisoner_flavor",    "모든 성장의 시작점." },
                { "char_mercenary_flavor",   "전투에 특화된 캐릭터." },
                { "char_miner_flavor",       "블록 파괴에 특화된 캐릭터." },
                { "char_graverobber_flavor", "희귀 자원 수급에 특화된 캐릭터." },
                { "run_setup_passive_label", "패시브" },
                { "run_setup_passive_level_fmt", "Lv.{0} / {1}" },

                // Event titles
                { "event_chest_title", "보물 상자" },
                { "event_tomb_title", "고대의 무덤" },
                { "event_chest_desc", "오래된 광부의 보급 상자를 발견했습니다! 업그레이드 하나를 선택하세요:" },
                { "event_tomb_desc", "어둠 속에 섬뜩한 무덤이 놓여 있습니다. 이 룬을 읽으면 강력한 버프를 얻지만, 무거운 저주가 따릅니다..." },
                
                // Buffs & Curses Choice Options
                { "event_opt_mining_title", "채굴 장비 업그레이드" },
                { "event_opt_mining_desc", "공격력 증가 (+1)" },
                { "event_opt_hp_title", "하트 크리스탈" },
                { "event_opt_hp_desc", "최대 체력 증가 (+2)" },
                { "event_opt_inv_title", "인벤토리 확장" },
                { "event_opt_inv_desc", "인벤토리 용량 증가 (+5)" },
                { "event_opt_stealth_title", "은신의 망토" },
                { "event_opt_stealth_desc", "몬스터 조우 확률 감소 (-15%)" },
                { "event_opt_hat_title", "안전모" },
                { "event_opt_hat_desc", "위험/함정 조우 확률 감소 (-15%)" },
                { "event_opt_demonic_title", "악마의 힘" },
                { "event_opt_demonic_desc", "공격력 대폭 증가 (+2)\n저주: 최대 체력 감소 (-2)" },
                { "event_opt_greed_title", "탐욕의 계약" },
                { "event_opt_greed_desc", "인벤토리 용량 대폭 증가 (+10)\n저주: 몬스터 조우 확률 증가 (+25%)" },
                { "event_opt_fortitude_title", "금지된 인내" },
                { "event_opt_fortitude_desc", "최대 체력 증가 (+4)\n저주: 몬스터 조우 시 즉시 피해 (-1 HP)" },
                { "event_opt_reckless_title", "무모한 타격" },
                { "event_opt_reckless_desc", "공격력 대폭 증가 (+2)\n저주: 채굴 시 15% 확률로 헛스윙" },
                { "event_opt_vampiric_title", "흡혈귀의 눈" },
                { "event_opt_vampiric_desc", "공격력 증가 (+2)\n저주: 몬스터 조우 시 즉시 피해 (-1 체력)" },

                // Boss Translations
                { "boss_title", "보스" },
                { "boss_rat_name", "거대 동굴쥐" },
                { "boss_spider_name", "여왕 거미" },
                { "boss_golem_name", "암석 골렘" },
                { "boss_worm_name", "용암 벌레" },
                { "boss_titan_name", "수정 거신" },
                { "boss_stone_golem_name", "돌 골렘" },
                { "boss_mother_cave_spider_name", "어미 동굴거미" },
                { "boss_skeleton_warlord_name", "해골 군주" },
                { "boss_all_metal_colossus_name", "전금속 거신" },
                { "boss_reward_title", "보스 처치 완료" },
                { "boss_reward_subtitle", "이번 런 동안 유지될 강력한 버프 1개를 선택하세요:" },
                { "boss_buff_atk", "공격력 +2" },
                { "boss_buff_atk_desc", "이번 런 동안 공격력이 2 증가합니다." },
                { "boss_buff_hp", "최대 체력 +5" },
                { "boss_buff_hp_desc", "이번 런 동안 최대 체력이 5 증가하고 체력을 5 회복합니다." },
                { "boss_buff_mining", "채굴력 +2" },
                { "boss_buff_mining_desc", "이번 런 동안 채굴력이 2 증가합니다." },
                { "boss_buff_mineral", "광물 획득량 +20%" },
                { "boss_buff_mineral_desc", "이번 런 동안 획득하는 광물이 20% 증가합니다." },
                { "boss_buff_spawn", "몬스터 조우 확률 -20%" },
                { "boss_buff_spawn_desc", "이번 런 동안 일반 몬스터 등장 확률이 20% 감소합니다." },
                { "boss_fixed_heal_hp", "체력 회복" },
                { "boss_fixed_heal_hp_desc", "최대 체력의 30%를 즉시 회복합니다." },
                { "boss_buff_heal", "회복 아이템 드랍률 +15%" },
                { "boss_buff_heal_desc", "이번 런 동안 전투 승리 시 회복 아이템 드랍률이 15% 증가합니다." },
                { "boss_rare_revive", "사망 시 1회 부활" },
                { "boss_rare_revive_desc", "사망 시 50% 체력으로 즉시 1회 부활합니다 (희귀)." },
                { "boss_rare_boss_dmg", "보스 사냥꾼" },
                { "boss_rare_boss_dmg_desc", "보스 몬스터에게 주는 피해가 50% 증가합니다 (희귀)." },
                { "boss_rare_mineral_50", "광부의 대박" },
                { "boss_rare_mineral_50_desc", "이번 런 동안 모든 광물 획득량이 50% 증가합니다 (희귀)." },
                { "boss_rare_event_double", "이중 축복" },
                { "boss_rare_event_double_desc", "이벤트 선택으로 얻는 버프 효과가 2배로 증가합니다 (희귀)." },
                { "boss_rare_immortality_potion", "불사 물약" },
                { "boss_rare_immortality_potion_desc", "불사 물약을 획득합니다 (희귀)." },
                
                // Effect System
                { "hud_relic_btn", "유물" },
                { "hud_inventory_btn", "가방" },
                { "relic_popup_title", "유물 및 효과" },
                { "inventory_popup_title", "가방 정보" },
                { "relic_popup_type_label", "종류 : {0}" },
                { "relic_popup_effect_label", "효과 : {0}" },

                // Inventory System
                { "hud_quantity_label", "보유 수량:" },
                { "hud_hp_heal", "체력 회복!" },
                { "inv_confirm_drop_title", "정말 버리시겠습니까?" },
                { "inv_confirm_discard_all_title", "전부 버리시겠습니까?" },
                { "inv_confirm_yes", "확인" },
                { "inv_confirm_no", "취소" },
                { "inv_empty_message", "보유 중인 아이템이 없습니다." },
                { "inv_dropped_fmt", "{0} 버림" },
                { "item_used_generic_fmt", "{0} 사용" },
                { "chest_reward_result_fmt", "체력 +{0}, {1}" },
                { "chest_reward_iron_fmt", "철 +{0}" },
                { "chest_reward_silver_fmt", "은 +{0}" },
                { "chest_reward_anvil_fmt", "간이 모루 +{0}" },
                { "chest_reward_gold_fmt", "금 +{0}" },
                { "map_title", "지도" },
                { "passive_max_level", "MAX" },
                { "passive_not_upgraded", "미강화" },
                { "status_burn_applied_msg", "화상!" },
                { "upgrade_passive_btn", "강화" },
                { "item_stone_name", "돌" },
                { "item_stone_desc", "단단한 돌멩이다." },
                { "item_wood_name", "뿌리" },
                { "item_wood_desc", "약효가 있는 뿌리다. 사용 시 체력을 1 회복한다." },
                { "item_iron_name", "철" },
                { "item_iron_desc", "차가운 철 광석이다. 장비 제작 등에 쓰인다." },
                { "item_silver_name", "은" },
                { "item_silver_desc", "빛나는 은 광석이다." },
                { "item_gold_name", "금" },
                { "item_gold_desc", "번쩍이는 금 광석이다." },
                { "item_diamond_name", "다이아" },
                { "item_diamond_desc", "눈부시게 빛나는 다이아몬드이다." },
                { "item_potion_name", "회복약" },
                { "item_potion_desc", "체력을 5 회복한다." },
                { "item_potion_medium_name", "회복약(중)" },
                { "item_potion_medium_desc", "체력을 10 회복한다." },
                { "item_potion_large_name", "회복약(대)" },
                { "item_potion_large_desc", "체력을 20 회복한다." },
                { "item_burn_cure_name", "화상 치료제" },
                { "item_burn_cure_desc", "화상 상태를 즉시 치료합니다." },
                { "item_burn_cure_used", "화상이 치료되었습니다." },
                { "item_burn_cure_no_burn", "현재 화상 상태가 아닙니다." },
                { "item_key_name", "열쇠" },
                { "item_key_desc", "굳게 닫힌 상자를 열 수 있을 것 같다." },
                { "item_chest_name", "보물상자" },
                { "item_chest_desc", "무언가 좋은 것이 들어있을 것 같은 상자다." },
                { "item_special_name", "특수 소모품" },
                { "item_special_desc", "신비로운 에너지가 깃든 특수 소모품이다. 사용 시 체력을 10 회복한다." },
                
                { "effect_type_CharacterPassive", "CharacterPassive" },
                { "effect_type_BossReward", "BossReward" },
                { "effect_type_Buff", "Buff" },
                { "effect_type_Debuff", "Debuff" },
                { "effect_type_Special", "Special" },
                
                { "effect_passive_miner_desc", "채굴력 +1" },
                { "effect_passive_mercenary_desc", "공격력 +1" },
                { "effect_passive_miner_value_fmt", "채굴력 +{0}" },
                { "effect_passive_mercenary_value_fmt", "공격력 +{0}" },
                { "effect_passive_graverobber_desc", "철/은/금/다이아 획득 시 10% 확률로 10% 추가 획득" },
                
                { "effect_buff_attack_name", "공격력 증가" },
                { "effect_buff_attack_desc", "공격력 +{0}" },
                { "effect_buff_maxhp_name", "최대 체력 증가" },
                { "effect_buff_maxhp_desc", "최대 체력 +{0}" },
                { "effect_buff_inventory_name", "가방 확장" },
                { "effect_buff_inventory_desc", "인벤토리 크기 +{0}" },
                { "effect_buff_monsterspawn_name", "안전 지대" },
                { "effect_buff_monsterspawn_desc", "몬스터 조우 확률 -{0}%" },
                { "effect_buff_hazardspawn_name", "안전 장비" },
                { "effect_buff_hazardspawn_desc", "함정 조우 확률 -{0}%" },
                
                { "effect_curse_attack_name", "쇠약의 저주" },
                { "effect_curse_attack_desc", "공격력 -{0}" },
                { "effect_curse_maxhp_name", "쇠퇴의 저주" },
                { "effect_curse_maxhp_desc", "최대 체력 -{0}" },
                { "effect_curse_monsterspawn_name", "불길한 저주" },
                { "effect_curse_monsterspawn_desc", "몬스터 조우 확률 +{0}%" },
                { "effect_curse_hazardspawn_name", "재앙의 저주" },
                { "effect_curse_hazardspawn_desc", "함정 조우 확률 +{0}%" },
                { "effect_curse_instantdamage_name", "피의 저주" },
                { "effect_curse_instantdamage_desc", "몬스터 조우 시 즉시 피해 -{0} 체력" },
                { "effect_curse_miningfail_name", "부서진 장비" },
                { "effect_curse_miningfail_desc", "채굴 실패 확률 +{0}%" },
                
                { "effect_boss_attack_name", "거대 쥐 토벌자" },
                { "effect_boss_attack_desc", "공격력 +2" },
                { "effect_boss_maxhp_name", "보스의 굳건함" },
                { "effect_boss_maxhp_desc", "최대 체력 +5" },
                { "effect_boss_mining_name", "파괴자" },
                { "effect_boss_mining_desc", "채굴력 +2" },
                { "effect_boss_mineral20_name", "탐욕의 상징" },
                { "effect_boss_mineral20_desc", "광물 획득량 +20%" },
                { "effect_boss_spawndecrease_name", "잠행" },
                { "effect_boss_spawndecrease_desc", "몬스터 조우 확률 -20%" },
                { "effect_boss_healdrop_name", "생명의 정수" },
                { "effect_boss_healdrop_desc", "처치 시 체력 회복 확률 +15%" },
                { "effect_boss_revive_name", "불사조의 깃털" },
                { "effect_boss_revive_desc", "사망 시 1회 부활 (체력 100% 회복)" },
                { "effect_boss_bossdamage_name", "거수 사냥꾼" },
                { "effect_boss_bossdamage_desc", "보스에게 주는 데미지 +50%" },
                { "effect_boss_mineral50_name", "대부호" },
                { "effect_boss_mineral50_desc", "광물 획득량 +50%" },
                { "effect_boss_doubleevent_name", "이중 축복" },
                { "effect_boss_doubleevent_desc", "이벤트 선택 시 얻는 버프 효과 2배" },
                { "effect_boss_immortality_potion_name", "불사 물약" },
                { "effect_boss_immortality_potion_desc", "불사 물약 획득" },

                { "item_portable_anvil_name", "간이 모루" },
                { "item_portable_anvil_desc", "휴대 가능한 작은 모루. 사용 시 곡괭이 내구도를 즉시 5 회복한다." },
                { "item_immortality_potion_name", "불사 물약" },
                { "item_immortality_potion_desc", "죽음의 순간 자동으로 복용된다. 한 번만 발동하며 체력 5로 부활한다." },
                { "item_anvil_full", "내구도가 이미 최대입니다." },
                { "item_auto_use", "자동 사용" },
                { "item_poison_cure_used", "중독이 치료되었습니다." },
                { "item_poison_cure_no_poison", "현재 중독 상태가 아닙니다." },
                { "item_combat_only", "전투 중에만 사용할 수 있습니다." },

                { "item_repair_kit_name", "수리 키트" },
                { "item_repair_kit_desc", "사용 시 곡괭이 내구도를 즉시 3 회복한다." },
                { "item_antidote_potion_name", "해독제" },
                { "item_antidote_potion_desc", "중독 상태를 즉시 치료한다." },
                { "item_bomb_name", "폭탄" },
                { "item_bomb_desc", "전투 중인 몬스터 전체에게 5의 피해를 준다. 전투 중에만 사용 가능." },
                { "item_holy_water_name", "정화의 성수" },
                { "item_holy_water_desc", "화상과 중독 상태를 동시에 치료한다." },
                { "item_enhanced_repair_kit_name", "강화 수리 키트" },
                { "item_enhanced_repair_kit_desc", "사용 시 곡괭이 내구도를 즉시 10 회복한다." },
                { "item_enhanced_bomb_name", "강화 폭탄" },
                { "item_enhanced_bomb_desc", "전투 중인 몬스터 전체에게 15의 피해를 준다. 전투 중에만 사용 가능." },
                { "item_angel_feather_name", "천사의 깃털" },
                { "item_angel_feather_desc", "체력을 완전히 회복하고 화상과 중독을 모두 치료한다." },
                { "item_full_repair_kit_name", "완전 수리 키트" },
                { "item_full_repair_kit_desc", "사용 시 곡괭이 내구도를 완전히 회복한다." },
                { "item_guardian_heart_name", "수호자의 심장" },
                { "item_guardian_heart_desc", "죽음의 순간 자동으로 발동한다. 한 번만 발동하며 체력 15로 부활한다." },

                { "merchant_title", "떠돌이 상점" },
                { "merchant_leave_button", "나가기" },
                { "merchant_sold_out", "SOLD OUT" },
                { "merchant_relic_section_label", "유물" },
                { "merchant_consumable_section_label", "소비 아이템" },
                { "merchant_potion_section_label", "포션" },
                { "merchant_featured_label", "오늘의 추천" },
                { "merchant_discount_banner_all_fmt", "오늘은 전체 상품 {0}% 할인!" },
                { "merchant_discount_banner_relic_fmt", "오늘은 희귀 유물 {0}% 할인!" },
                { "merchant_hp_full", "체력이 최대입니다." },
                { "merchant_currency_fmt", "은 {0}  금 {1}  다이아 {2}  뿌리 {3}" },

                { "battle_player_turn", "플레이어 턴" },
                { "battle_monster_turn", "적 턴" },
                { "intent_attack_desc", "공격" },
                { "intent_heavy_attack_desc", "강공격" },
                { "intent_defend_desc", "방어" },
                { "intent_buff_desc", "버프" },
                { "intent_debuff_desc", "디버프" },
                { "intent_heal_desc", "회복" },
                { "intent_summon_desc", "소환" },
                { "intent_special_desc", "특수기" },

                { "merchant_quote_01", "오늘도 살아남았군." },
                { "merchant_quote_02", "깊은 곳일수록 좋은 물건이 있지." },
                { "merchant_quote_03", "목숨보다 비싼 건 없다네." },
                { "merchant_quote_04", "유물은 주인을 선택하지." },
                { "merchant_quote_05", "천천히 둘러보게. 다 사연이 있는 물건들이야." },
                { "merchant_quote_06", "목숨 걸 가치가 있는 것만 취급한다네." },
                { "merchant_quote_07", "조심하게, 개중엔 물어뜯는 놈도 있으니." },
                { "merchant_quote_08", "이 광산 어디서도 못 구할 물건이지." },
                { "merchant_quote_09", "금은 여기서도 위에서도 똑같이 쳐준다네." },
                { "merchant_quote_10", "자네보다 나은 손님도 여럿 묻었지." },
                { "merchant_quote_11", "물건마다 값이 있는 법이지. 싼 것도 마찬가지고." },
                { "merchant_quote_12", "꾸물대지 말게. 어둠은 기다려주지 않아." },
                { "merchant_quote_13", "이런 유물로 흥한 자도 망한 자도 봤다네." },
                { "merchant_quote_14", "현명한 광부는 깊이가 삼키기 전에 쓰는 법이지." },
                { "merchant_quote_15", "오늘 운이 좋은가?" },
                { "merchant_quote_16", "저건 저주받았을 걸세. 아마도." },
                { "merchant_quote_17", "나는 절박한 자들이 있는 곳을 찾아다니지." },
                { "merchant_quote_18", "나중에 고마워하게 될 걸세. 아니면 말고." },
                { "merchant_quote_19", "광산이 위험할수록 장사는 잘 되는 법이지." },
                { "merchant_quote_20", "지금 사게. 후회는 없을 걸세." },
                { "merchant_quote_21", "금이 어디서 났는지는 묻지 않는다네." },
                { "merchant_quote_22", "늘 다시 찾아오는 손님이 있기 마련이지." },
                { "merchant_quote_23", "포션을 찾는 이도, 희망을 찾는 이도 있지." },
                { "merchant_quote_24", "내가 판 유물 중 주인을 하나쯤 죽이지 않은 게 없다네." },
                { "merchant_quote_legendary_relic", "이건 평생 기억할 만한 물건이군." },
                { "merchant_quote_legendary_item", "이런 물건은 평생 한 번 볼까 말까 하지." },
                { "merchant_quote_no_funds", "돈을 좀 더 모아서 다시 오게." },

                { "hud_pickaxe_broken", "파손" },
                { "pickaxe_broken_alert_title", "곡괭이가 파손되었습니다." },
                { "pickaxe_broken_alert_desc", "이제 채굴 시 체력을 소모합니다." },
                { "pickaxe_repair_full", "내구도가 이미 최대입니다." },
                { "pickaxe_repair_not_enough", "재료가 부족합니다." },

                // 업적 이름/설명
                { "ach_first_step_name", "첫 발걸음" },
                { "ach_first_step_desc", "첫 번째 런을 시작합니다." },
                { "ach_depth50_name", "50미 아래로" },
                { "ach_depth50_desc", "깊이 50에 도달합니다." },
                { "ach_depth100_name", "심연을 향해" },
                { "ach_depth100_desc", "깊이 100에 도달합니다." },
                { "ach_depth200_name", "지하 심층" },
                { "ach_depth200_desc", "깊이 200에 도달합니다." },
                { "ach_kill10_name", "몬스터 사냥꾼" },
                { "ach_kill10_desc", "몬스터 10마리를 처치합니다." },
                { "ach_kill50_name", "해충 구제사" },
                { "ach_kill50_desc", "몬스터 50마리를 처치합니다." },
                { "ach_boss_first_name", "첫 번째 피" },
                { "ach_boss_first_desc", "첫 번째 보스를 처치합니다." },
                { "ach_boss_cave_rat_name", "쥐 사냥꾼" },
                { "ach_boss_cave_rat_desc", "동굴쥐 보스를 처치합니다." },
                { "ach_ore_iron50_name", "철의 의지" },
                { "ach_ore_iron50_desc", "철 광석을 50개 채굴합니다." },
                { "ach_ore_diamond10_name", "다이아몬드 사냥꾼" },
                { "ach_ore_diamond10_desc", "다이아몬드 광석을 10개 채굴합니다." },
                { "ach_relic1_name", "수집가" },
                { "ach_relic1_desc", "처음으로 유물을 수집합니다." },
                { "ach_relic5_name", "사재기꾼" },
                { "ach_relic5_desc", "유물을 5개 수집합니다." },
                { "ach_death1_name", "아프다" },
                { "ach_death1_desc", "처음으로 사망합니다." },
                { "ach_repair1_name", "수리공" },
                { "ach_repair1_desc", "곡괭이를 한 번 수리합니다." },
                { "ach_lava1_name", "불장난" },
                { "ach_lava1_desc", "용암 조우에서 살아남습니다." },
                { "ach_treasure5_name", "보물 사냥꾼" },
                { "ach_treasure5_desc", "보물 상자를 5개 엽니다." },

                { "effect_type_StatusEffect", "상태이상" },

                { "status_burn_name", "화상" },
                { "status_burn_desc", "행동 시 화상 피해를 입는 지속 상태이상" },

                { "status_mining_down_name", "채굴력 감소" },
                { "status_mining_down_desc", "채굴력이 감소합니다." },
                { "status_mining_up_name", "채굴력 증가" },
                { "status_mining_up_desc", "채굴력이 증가합니다." },

                { "reveal_monster_slime", "슬라임 발견!" },
                { "monster_slime_name", "슬라임" },
                { "monster_small_slime_name", "작은 슬라임" },
                { "monster_skeleton_name", "스켈레톤" },
                { "monster_armored_skeleton_name", "갑옷 스켈레톤" },
                { "monster_mimic_name", "미믹" },

                { "relic_heat_resistant_charm_name", "내열 부적" },
                { "relic_heat_resistant_charm_desc", "화상 지속 시간 3턴 감소" },
                { "relic_frozen_crystal_name", "냉동 수정" },
                { "relic_frozen_crystal_desc", "화상 피해 1 감소" },
                { "relic_firefighter_helmet_name", "소방관 헬멧" },
                { "relic_firefighter_helmet_desc", "화상 지속 2턴, 피해 1 감소" },
                { "relic_purification_ring_name", "정화의 반지" },
                { "relic_purification_ring_desc", "50% 확률로 화상 무효" },
                { "relic_burning_heart_name", "불타는 심장" },
                { "relic_burning_heart_desc", "공격력 +2, 화상 지속 시간 3턴 증가" },
                { "relic_lava_contract_name", "용암 계약" },
                { "relic_lava_contract_desc", "광물 획득량 +25%, 화상 피해 1 증가" },
                { "relic_cursed_ash_name", "저주받은 재" },
                { "relic_cursed_ash_desc", "최대 체력 +5, 화상 지속 시간 5턴 증가" },
                { "relic_fire_cult_mask_name", "불의 교단 가면" },
                { "relic_fire_cult_mask_desc", "몬스터 공격력 +2, 화상 피해 2 증가" },

                // 상점 탭
                { "shop_tab_pickaxe",    "곡괭이" },
                { "shop_tab_character",  "캐릭터" },
                { "shop_tab_consumable", "아이템" },
                { "shop_tab_special",    "특수" },
                { "shop_owned",          "보유 중" },
                { "shop_info_select",    "상품을 선택하세요" },

                // 곡괭이 상점
                { "shop_pickaxe_title",        "곡괭이" },
                { "shop_pickaxe_mining_power", "⛏ 채굴력: {0}" },
                { "shop_pickaxe_durability",   "♦ 최대 내구도: {0}" },
                { "shop_pickaxe_buy",          "구매" },
                { "shop_pickaxe_equip",        "장착" },
                { "shop_pickaxe_equipped",     "장착 중" },

                { "pickaxe_wood_name",    "나무 곡괭이" },
                { "pickaxe_wood_desc",    "기본 곡괭이. 튼튼하지만 약하다." },
                { "pickaxe_iron_name",    "철 곡괭이" },
                { "pickaxe_iron_desc",    "철로 단조된 곡괭이. 광석을 더 빠르게 부순다." },
                { "pickaxe_silver_name",  "은 곡괭이" },
                { "pickaxe_silver_desc",  "정제된 곡괭이. 돌을 쉽게 뚫는다." },
                { "pickaxe_gold_name",    "금 곡괭이" },
                { "pickaxe_gold_desc",    "강력한 힘을 가진 묵직한 곡괭이." },
                { "pickaxe_diamond_name", "다이아 곡괭이" },
                { "pickaxe_diamond_desc", "최강의 곡괭이. 무엇도 막을 수 없다." },

                // 채굴력 버프/디버프 효과
                { "effect_buff_mining_name", "채굴력 증가" },
                { "effect_buff_mining_desc", "채굴력 +{0}" },
                { "effect_curse_mining_name", "채굴력 저주" },
                { "effect_curse_mining_desc", "채굴력 -{0}" },

                // 신규 보물 유물 - 채굴 계열
                { "relic_miners_gloves_name", "광부의 장갑" },
                { "relic_miners_gloves_desc", "채굴력 +1" },
                { "relic_mining_king_helmet_name", "채굴왕의 헬멧" },
                { "relic_mining_king_helmet_desc", "채굴력 +2" },
                { "relic_broken_drill_name", "부서진 드릴" },
                { "relic_broken_drill_desc", "채굴력 +3, 최대 체력 -5" },
                { "relic_ore_detector_name", "광맥 탐지기" },
                { "relic_ore_detector_desc", "채굴력 +1, 광물 획득량 +20%" },

                // 신규 보물 유물 - 전투 계열
                { "relic_warriors_ring_name", "전사의 반지" },
                { "relic_warriors_ring_desc", "공격력 +1" },
                { "relic_mercenary_medal_name", "용병의 훈장" },
                { "relic_mercenary_medal_desc", "공격력 +2" },
                { "relic_blood_contract_name", "피의 계약서" },
                { "relic_blood_contract_desc", "공격력 +3, 최대 체력 -5" },
                { "relic_hunters_eye_name", "사냥꾼의 눈" },
                { "relic_hunters_eye_desc", "공격력 +1, 곡괭이 내구도 -2" },

                // 신규 무덤 저주 유물
                { "relic_cursed_pickaxe_name", "저주받은 곡괭이" },
                { "relic_cursed_pickaxe_desc", "채굴력 +2, 화상 피해 +1" },
                { "relic_madness_sword_name", "광기의 검" },
                { "relic_madness_sword_desc", "공격력 +2, 곡괭이 내구도 -3" },
                { "relic_cursed_mining_gloves_name", "저주받은 채굴 장갑" },
                { "relic_cursed_mining_gloves_desc", "채굴력 +1, 최대 체력 -3" },
                { "relic_blood_rune_name", "피의 룬" },
                { "relic_blood_rune_desc", "공격력 +1, 화상 지속 시간 +2턴" },

                // Run Setup
                { "run_setup_title",  "탐험 준비" },
                { "run_setup_start",  "탐험 시작!" },
                { "run_setup_char_label",    "캐릭터" },
                { "run_setup_pickaxe_label", "곡괭이" },

                // Loading steps
                { "loading_init",               "초기화 중..." },
                { "loading_assets",             "에셋 로드 중..." },
                { "loading_save",               "저장 데이터 로드 중..." },
                { "loading_preparing",          "준비 중..." },
                { "loading_ready",              "준비 완료!" },
                { "loading_step_playerdata",    "플레이어 데이터 로드 중..." },
                { "loading_step_rundata",       "런 데이터 생성 중..." },
                { "loading_step_character",     "캐릭터 적용 중..." },
                { "loading_step_pickaxe",       "곡괭이 장착 중..." },
                { "loading_step_items",         "시작 아이템 지급 중..." },
                { "loading_step_passive",       "패시브 적용 중..." },
                { "loading_step_stats",         "기본 스탯 계산 중..." },
                { "loading_step_runreset",      "런 상태 초기화 중..." },
                { "loading_step_assets",        "게임 에셋 로드 중..." },
                { "loading_step_pools",         "오브젝트 풀 초기화 중..." },
                { "loading_step_locale",        "번역 데이터 로드 중..." },
                { "loading_step_sound",         "사운드 로드 중..." },
                { "loading_step_verify",        "데이터 검증 중..." },
                { "loading_step_enter",         "지하 세계로 입장 중..." },
                { "loading_tip_cave",           "깊이 내려갈수록 몬스터가 강해집니다..." },

                // 런 종료
                { "exit_run_btn",         "런 종료" },
                { "exit_run_confirm_msg", "현재 진행 중인 런을 종료하시겠습니까?\n획득한 모든 런 진행 정보는 사라집니다." },
                { "exit_run_cancel_btn",  "취소" },
                { "exit_run_confirm_btn", "런 종료" },

                // 노드 이벤트 — 공통
                { "event_btn_continue",              "계속" },
                { "event_btn_continue_desc",         "확인하고 계속 진행한다." },

                // 노드 이벤트 — 부정
                { "event_rockfall_title",            "낙석 발생!" },
                { "event_rockfall_desc",             "천장이 무너진다. 피할 것인가, 맞을 것인가?" },
                { "event_rockfall_dodge_title",      "① 피하기 (턴 +2)" },
                { "event_rockfall_dodge_desc",       "잔해를 돌아가느라 2턴을 더 소모한다." },
                { "event_rockfall_hit_title",        "② 맞고 채굴 (HP-2, 철광석×2)" },
                { "event_rockfall_hit_desc",         "충격을 견디고 낙석에서 광석을 얻는다." },
                { "event_rockfall_dodge",            "잔해를 조심스럽게 피했다." },

                { "event_poisonmist_title",          "독 안개" },
                { "event_poisonmist_desc",           "균열에서 독성 안개가 스며든다. 빨리 행동하라!" },
                { "event_poisonmist_inhale_title",   "① 흡입 (공격력 -10%, 6턴)" },
                { "event_poisonmist_inhale_desc",    "독 안개를 들이마셔 6턴간 공격이 약해진다." },
                { "event_poisonmist_rush_title",     "② 질주 (광물 5개 소비)" },
                { "event_poisonmist_rush_desc",      "광물을 던져 주의를 끌고 빠져나간다 (다이아 > 금 > 은 > 철)." },

                { "event_spiketrap_title",           "가시 함정!" },
                { "event_spiketrap_desc",            "발밑에 숨겨진 함정이 작동했다!" },
                { "event_spiketrap_detour_title",    "① 우회 (턴 +3)" },
                { "event_spiketrap_detour_desc",     "먼 길을 돌아간다. 3턴을 소모한다." },
                { "event_spiketrap_dash_title",      "② 질주 (70% 안전 / 30% HP-3)" },
                { "event_spiketrap_dash_desc",       "함정을 뛰어넘는다. 30% 확률로 3 데미지." },
                { "event_trap_detour",               "먼 길을 돌아왔다." },
                { "event_trap_safe",                 "다치지 않고 통과했다!" },

                { "event_collapsedtunnel_title",     "붕괴된 터널" },
                { "event_collapsedtunnel_desc",      "앞길이 막혔다! 곡괭이로 간신히 뚫었지만 내구도가 크게 손상됐다. 다음 경로 노드를 건너뛴다." },

                { "event_darkaltar_title",           "어둠의 제단" },
                { "event_darkaltar_desc",            "음침한 제단이 어두운 에너지를 발산한다. 피를 바칠 것인가?" },
                { "event_darkaltar_offer_title",     "① 피 바치기 (HP-5, 랜덤 유물)" },
                { "event_darkaltar_offer_desc",      "5 HP를 희생해 어둠 속 유물을 얻는다." },
                { "event_darkaltar_skip_title",      "② 지나치기" },
                { "event_darkaltar_skip_desc",       "제단을 무시하고 계속 내려간다." },

                { "event_lostspirit_title",          "길 잃은 영혼" },
                { "event_lostspirit_desc",           "방황하는 영혼이 길을 막고 조공을 요구한다." },
                { "event_lostspirit_appease_title",  "① 달래기 (광물 5개, 랜덤 버프)" },
                { "event_lostspirit_appease_desc",   "광물을 바쳐 영혼을 진정시킨다. 랜덤 능력을 얻는다." },
                { "event_lostspirit_ignore_title",   "② 무시하기 (다음 몬스터 공격+1)" },
                { "event_lostspirit_ignore_desc",    "억지로 지나친다. 영혼이 다음 전투를 저주한다." },
                { "event_spirit_appeased",           "영혼이 물러나며 은혜를 남겼다." },
                { "event_spirit_angered",            "영혼의 저주가 떠돈다..." },

                // 노드 이벤트 — 긍정
                { "event_camp_title",                "버려진 야영지" },
                { "event_camp_desc",                 "오래된 광부의 야영지를 발견했다! 잠시 쉬며 체력을 회복한다." },

                { "event_richore_title",             "풍부한 광맥" },
                { "event_richore_desc",              "반짝이는 광맥이 눈앞에 펼쳐진다. 얼마나 깊이 캘 것인가?" },
                { "event_richore_normal_title",      "① 일반 채굴 (철×3, 은×2, 금×1)" },
                { "event_richore_normal_desc",       "안전하게 채굴한다." },
                { "event_richore_intense_title",     "② 집중 채굴 (×3 광석, 20% 엘리트 조우)" },
                { "event_richore_intense_desc",      "광맥을 완전히 긁어낸다 — 소음이 엘리트 몬스터를 부를 수 있다." },
                { "event_rich_ore_elite",            "소음이 무언가를 끌어들였다..." },


                { "event_hotspring_title",           "온천" },
                { "event_hotspring_desc",            "숨겨진 온천에서 수증기가 피어오른다. 치유의 물에 몸을 담근다." },

                { "event_equipment_title",           "버려진 장비" },
                { "event_equipment_desc",            "광부가 남기고 간 장비 더미. 쓸만한 것이 있을지 모른다." },

                { "event_journal_title",             "광부의 일지" },
                { "event_journal_desc",              "풍부한 광맥에 대한 메모가 가득한 낡은 일지. 읽으면 다음 20 노드 동안 광석 획득이 늘어난다." },

                { "event_shrine_title",              "수정 성소" },
                { "event_shrine_desc",              "빛나는 수정 성소. 에너지가 흘러든다 — 축복을 선택하라." },
                { "event_shrine_atk",                "① 공격의 축복 (공격+1)" },
                { "event_shrine_atk_desc",           "수정이 전투 본능을 예리하게 만든다." },
                { "event_shrine_mining",             "② 채굴의 축복 (채굴+1)" },
                { "event_shrine_mining_desc",        "수정이 곡괭이 타격을 강화한다." },
                { "event_shrine_hp",                 "③ 생명의 축복 (최대HP+2)" },
                { "event_shrine_hp_desc",            "수정이 몸을 강인하게 만든다." },
                { "event_shrine_spawn",              "④ 수호의 축복 (몬스터 출현율-15%)" },
                { "event_shrine_spawn_desc",         "수정이 몬스터로부터 몸을 숨겨준다." },

                { "event_merchant_no_funds",         "재료가 부족합니다!" },

                { "event_forge_title",               "고대 용광로" },
                { "event_forge_desc",                "오래된 문명의 아직 타오르는 용광로. 사용할 것인가?" },
                { "event_forge_atk_title",           "① 무기 날 단련 (공격+1 / 금×5)" },
                { "event_forge_atk_desc",            "고대 모루에 무기를 벼린다." },
                { "event_forge_mining_title",        "② 곡괭이 강화 (채굴+1 / 철×5)" },
                { "event_forge_mining_desc",         "철로 곡괭이 날을 강화한다." },
                { "event_forge_heal_title",          "③ 식량 제조 (HP+5 / 은×3)" },
                { "event_forge_heal_desc",           "은을 녹여 회복 식량을 만든다." },
                { "event_forge_skip_title",          "④ 그냥 떠나기" },
                { "event_forge_skip_desc",           "열기가 너무 강하다. 그냥 지나친다." },

                // 노드 이벤트 — 위험/보상
                { "event_devil_title",               "악마의 계약" },
                { "event_devil_desc",                "그림자 속 존재가 힘을 제안한다... 대가를 치르고." },
                { "event_devil_atk_title",           "① 공격 계약 (HP-20%, 공격+2)" },
                { "event_devil_atk_desc",            "최대 HP의 20%를 잃고 영구적으로 공격+2를 얻는다." },
                { "event_devil_mining_title",        "② 채굴 계약 (HP-20%, 채굴+2)" },
                { "event_devil_mining_desc",         "최대 HP의 20%를 잃고 영구적으로 채굴+2를 얻는다." },
                { "event_devil_skip_title",          "③ 거절" },
                { "event_devil_skip_desc",           "거래를 거부하고 자리를 뜬다." },

                { "event_minegod_title",             "광산신의 축복" },
                { "event_minegod_desc",              "심층의 고대 신이 당신을 주목한다. 하나의 축복을 선택하라." },
                { "event_minegod_atk_title",         "① 공격의 축복 (공격+1)" },
                { "event_minegod_atk_desc",          "신이 당신의 검날을 예리하게 한다." },
                { "event_minegod_mining_title",      "② 채굴의 축복 (채굴+1)" },
                { "event_minegod_mining_desc",       "신이 당신의 곡괭이에 힘을 불어넣는다." },
                { "event_minegod_hp_title",          "③ 생명의 축복 (최대HP+2)" },
                { "event_minegod_hp_desc",           "신이 당신의 육체를 강화한다." },

                // 상태 이상: 독
                { "status_poison_name",              "독" },
                { "status_poison_desc",              "지속 시간 동안 공격력이 10% 감소한다." },

                // 광석 획득 버프 (광부의 일지)
                { "effect_ore_gain_name",            "광맥 지식" },
                { "effect_ore_gain_desc",            "{0}개 노드 동안 광석 획득량 +20%." },

                // 유물 등급 이름
                { "relic_rarity_common",    "일반" },
                { "relic_rarity_rare",      "희귀" },
                { "relic_rarity_legendary", "전설" },

                // 유물 태그 이름
                { "relic_tag_mining",   "채굴" },
                { "relic_tag_combat",   "전투" },
                { "relic_tag_defense",  "방어" },
                { "relic_tag_economy",  "경제" },
                { "relic_tag_pickaxe",  "곡괭이" },
                { "relic_tag_healing",  "회복" },
                { "relic_tag_status",   "상태이상" },
                { "relic_tag_boss",     "보스" },
                { "relic_tag_elite",    "엘리트" },
                { "relic_tag_utility",  "유틸리티" },

                // 엘리트 몬스터
                { "monster_big_slime_name",       "거대 슬라임" },
                { "monster_big_slime_desc",       "처치 시 슬라임 3마리로 분열한다." },
                { "monster_skeleton_miner_name",  "해골 광부" },
                { "monster_skeleton_miner_desc",  "전투 중 주기적으로 광물을 훔친다." },
                { "monster_iron_spider_name",     "철판 거미" },
                { "monster_iron_spider_desc",     "철판 방어구가 있어 먼저 부숴야 한다. 방어구 파괴 후 3번 공격 시마다 독을 적용한다." },
                { "monster_merchant_mimic_name",  "상인 미믹" },
                { "monster_merchant_mimic_desc",  "희귀한 미믹. 처치 시 깊이에 따른 광물 보상을 준다." },
                { "monster_cursed_knight_name",   "저주받은 기사" },
                { "monster_cursed_knight_desc",   "체력 75%, 50%, 25% 시 격분 — 공격 속도와 피해 증가." },
                { "monster_cursed_priest_name",   "저주받은 사제" },
                { "monster_cursed_priest_desc",   "매 1초마다 공격력을 약화시킨다. 처치 시 디버프가 해제된다." },
                { "relic_miner_glove_name", "광부의 장갑" },
                { "relic_miner_glove_desc", "채굴력 +1" },
                { "relic_old_whetstone_name", "낡은 숫돌" },
                { "relic_old_whetstone_desc", "공격력 +1" },
                { "relic_sturdy_backpack_name", "튼튼한 배낭" },
                { "relic_sturdy_backpack_desc", "인벤토리 +5칸" },
                { "relic_emergency_bandage_name", "응급 붕대" },
                { "relic_emergency_bandage_desc", "전투 종료 시 HP +1 회복" },
                { "relic_reinforced_handle_name", "보강 손잡이" },
                { "relic_reinforced_handle_desc", "곡괭이 최대 내구도 +10" },
                { "relic_oil_bottle_name", "기름병" },
                { "relic_oil_bottle_desc", "곡괭이 내구도 감소량 20% 감소" },
                { "relic_iron_ornament_name", "철 곡괭이 장식" },
                { "relic_iron_ornament_desc", "철 획득량 +20%" },
                { "relic_silver_necklace_name", "은 목걸이" },
                { "relic_silver_necklace_desc", "은 획득량 +20%" },
                { "relic_gold_pouch_name", "금 주머니" },
                { "relic_gold_pouch_desc", "금 획득량 +20%" },
                { "relic_diamond_brooch_name", "다이아 브로치" },
                { "relic_diamond_brooch_desc", "다이아 획득량 +20%" },
                { "relic_miner_canteen_name", "광부의 물통" },
                { "relic_miner_canteen_desc", "화상 지속 턴 -2" },
                { "relic_work_glove_name", "작업용 장갑" },
                { "relic_work_glove_desc", "곡괭이 내구도 50% 이상 시 채굴력 +1" },
                { "relic_iron_boot_name", "철못 장화" },
                { "relic_iron_boot_desc", "Rockfall 및 Spike Trap 피해 -1" },
                { "relic_small_whetstone_name", "작은 숫돌" },
                { "relic_small_whetstone_desc", "엘리트 몬스터에게 주는 피해 +10%" },
                { "relic_lucky_pickaxe_name", "행운의 곡괭이" },
                { "relic_lucky_pickaxe_desc", "채굴 시 5% 확률로 동일 광물 1개 추가 획득" },
                { "relic_miner_lunchbox_name", "광산 도시락" },
                { "relic_miner_lunchbox_desc", "Boss 처치 후 HP +5 회복" },
                { "relic_leather_handle_name", "가죽 손잡이" },
                { "relic_leather_handle_desc", "곡괭이 내구도 감소량 10% 감소" },
                { "relic_mining_permit_name", "채굴 허가증" },
                { "relic_mining_permit_desc", "일반 몬스터 처치 시 20% 확률로 철 1개 추가 획득" },
                { "relic_auto_repair_kit_name", "자동 수리 키트" },
                { "relic_auto_repair_kit_desc", "몬스터 처치 시 곡괭이 내구도 +1" },
                { "relic_vampire_pickaxe_name", "흡혈 곡괭이" },
                { "relic_vampire_pickaxe_desc", "광물 채굴 시 10% 확률로 HP +1" },
                { "relic_ore_sensor_name", "광맥 탐지기" },
                { "relic_ore_sensor_desc", "광물 획득량 +30%" },
                { "relic_steel_heart_name", "강철 심장" },
                { "relic_steel_heart_desc", "최대 HP +10" },
                { "relic_mine_ring_name", "광산 반지" },
                { "relic_mine_ring_desc", "채굴력 +2" },
                { "relic_warrior_necklace_name", "전사의 목걸이" },
                { "relic_warrior_necklace_desc", "공격력 +2" },
                { "relic_magma_amulet_name", "마그마 부적" },
                { "relic_magma_amulet_desc", "화상 면역" },
                { "relic_waterproof_boot_name", "방수 장화" },
                { "relic_waterproof_boot_desc", "수몰 면역" },
                { "relic_poison_antidote_name", "독 해독제" },
                { "relic_poison_antidote_desc", "중독 면역" },
                { "relic_greedy_coin_name", "탐욕의 동전" },
                { "relic_greedy_coin_desc", "광물 획득량 +50%. 이벤트·유물 회복 포함 모든 HP 회복량이 절반으로 줄어든다." },
                { "relic_cursed_digger_name", "저주받은 곡괭이" },
                { "relic_cursed_digger_desc", "채굴력 +3  최대 HP -10" },
                { "relic_elite_hunter_medal_name", "엘리트 헌터 훈장" },
                { "relic_elite_hunter_medal_desc", "엘리트 몬스터 처치 시 추가 유물 보상 획득" },
                { "relic_god_pickaxe_name", "신의 곡괭이" },
                { "relic_god_pickaxe_desc", "채굴력 +5" },
                { "relic_mine_crown_name", "광산 왕관" },
                { "relic_mine_crown_desc", "모든 광물 획득량 2배" },
                { "relic_immortal_heart_name", "불사의 심장" },
                { "relic_immortal_heart_desc", "런 중 1회 사망 시 HP 30%로 부활" },
                { "relic_soul_contract_name", "영혼 계약서" },
                { "relic_soul_contract_desc", "공격력 +5  최대 HP -20" },
                { "relic_dragon_fang_name", "드래곤 송곳니" },
                { "relic_dragon_fang_desc", "몬스터에게 주는 피해 +50%" },
                { "relic_infinite_whetstone_name", "무한 숫돌" },
                { "relic_infinite_whetstone_desc", "곡괭이 내구도 감소 없음" },
                { "relic_mine_blessing_name", "광산 신의 축복" },
                { "relic_mine_blessing_desc", "공격력 +3  채굴력 +3  최대 HP +3" },
                { "relic_golden_bag_name", "황금 주머니" },
                { "relic_golden_bag_desc", "철·은·금·다이아 획득량 +50%" },
                { "relic_hourglass_name", "시간의 모래시계" },
                { "relic_hourglass_desc", "보스 처치 시 HP 전부 회복" },
                { "relic_abyssal_core_name", "심연의 핵" },
                { "relic_abyssal_core_desc", "엘리트 처치 보상 2배  (등장 확률 변경 없음)" },
            };

            _translations["en"] = en;
            _translations["ko"] = ko;
        }

        public string GetTranslation(string key)
        {
            string code = CurrentLanguageCode;
            if (string.IsNullOrEmpty(code) || !_translations.ContainsKey(code))
            {
                code = "en"; // Default fallback
            }

            if (_translations[code].TryGetValue(key, out string val))
            {
                return val;
            }

            // Fallback to English
            if (_translations["en"].TryGetValue(key, out string fallbackVal))
            {
                return fallbackVal;
            }

            return key; // Return key itself if not found
        }

        public string GetFormatted(string key, params object[] args)
        {
            try
            {
                string format = GetTranslation(key);
                return string.Format(format, args);
            }
            catch (Exception ex)
            {
                Debug.LogError($"Error formatting translation for key '{key}': {ex.Message}");
                return key;
            }
        }

        public void SetLanguage(string langCode)
        {
            if (langCode == "ko" || langCode == "en")
            {
                SaveManager.CurrentData.Language = langCode;
                SaveManager.Save();
                OnLanguageChanged?.Invoke();
            }
        }

        public void ToggleLanguage()
        {
            string next = (CurrentLanguageCode == "ko") ? "en" : "ko";
            SetLanguage(next);
        }
    }
}
